output "palo_alto_next_generation_firewall_virtual_hub_local_rulestacks" {
  description = "All palo_alto_next_generation_firewall_virtual_hub_local_rulestack resources"
  value       = azurerm_palo_alto_next_generation_firewall_virtual_hub_local_rulestack.palo_alto_next_generation_firewall_virtual_hub_local_rulestacks
}
