output "spring_cloud_application_insights_application_performance_monitorings" {
  description = "All spring_cloud_application_insights_application_performance_monitoring resources"
  value       = azurerm_spring_cloud_application_insights_application_performance_monitoring.spring_cloud_application_insights_application_performance_monitorings
}
