output "network_interface_application_gateway_backend_address_pool_associations" {
  description = "All network_interface_application_gateway_backend_address_pool_association resources"
  value       = azurerm_network_interface_application_gateway_backend_address_pool_association.network_interface_application_gateway_backend_address_pool_associations
}
