output "sentinel_data_connector_microsoft_defender_advanced_threat_protections" {
  description = "All sentinel_data_connector_microsoft_defender_advanced_threat_protection resources"
  value       = azurerm_sentinel_data_connector_microsoft_defender_advanced_threat_protection.sentinel_data_connector_microsoft_defender_advanced_threat_protections
}
